### ISSUE TITLE
Cannot install package after recent commit

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/Medicaid#131]
Just typed the following into a new session of R:
`devtools::install_github("PHSKC-APDE/claims_data")`

I received the following error:
    **Using github PAT from envvar GITHUB_PAT
    Error: Failed to install 'unknown package' from GitHub:
      Line starting '<<<<<<< HEAD ...' is malformed!**

Looks like there are remnants of a merge conflict in [Jeremy's commit on 9/20/2021] (link removed)?

**Comment by alastairmatheson** [comment]
Reverted to earlier commit and restored desired changes. Things should work now.
