### ISSUE TITLE
PHClaims.ref.ccw_lookup table is out of date

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/Medicaid#132]
Current table uses 2019-02 definions from CMS, latest definitions were updated in 2022-02 and include 3 new conditions. New algorithm format contains only ICD-10-CM codes and thus older definition file will have to be appended to newer one to capture both ICD-9-CM and ICD-10-CM codes.

**Comment by alastairmatheson** [comment]
Fixed in https://github.com/PHSKC-APDE/claims_data/pull/135
