### ISSUE TITLE
Update claims functions to work in HHSAW

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/Medicaid#137]
Most have hard-coded references to PHClaims and need to be more flexible. Also lots of opportunities to make the code more efficient.

**Comment by sarahlauffer** [comment]
Update medicaid data table structure/dictionary https://kc1.sharepoint.com/:x:/r/teams/DPH-KCCross-SectorData/_layouts/15/Doc.aspx?sourcedoc=%7B1FD93A1E-E35A-40A7-A9E3-E6331C61DDBE%7D&file=Medicaid%20data%20table%20structure.xlsx&action=default&mobileredirect=true

**Comment by kai-fukutaki** [comment]
Still issues with functions relying on stored procedures, so keeping this open

**Comment by kai-fukutaki** [comment]
Stored procedure functions will not be adapted
