### ISSUE TITLE
Add new CCW conditions to function

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/Medicaid#138]
https://github.com/PHSKC-APDE/claims_data/blob/673f8557b0bd2c1b663c7035cbd108db6b2e3319/R/claims_condition.R#L35

**Comment by kai-fukutaki** [comment]
@alastairmatheson I have a PR for this with the new conditions, but when testing the function with those new conditions I don't get any results back. Is that expected?

Conditions: ccw_cancer_urologic, ccw_non_alzheimer_dementia, ccw_parkinsons, ccw_pneumonia

**Comment by alastairmatheson** [comment]
All these are only available for ICD-10 (2017 onwards). What time frame are you using in the test? I checked and there are people with those conditions in the data:
`SELECT ccw_desc, count(*) as cnt   FROM [claims].[final_mcaid_claim_ccw] group by ccw_desc  order by ccw_desc`

**Comment by kai-fukutaki** [comment]
Ah ok I think it's just because I was looking in apcd source, but they are present when I use the function on mcaid source
