### ISSUE TITLE
ref dx_lookup table needs updating

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/Medicaid#160]
As new ICD codes are added, we need to add to the claims.ref_dx_lookup table and set up a process for maintaining it quarterly

**Comment by kai-fukutaki** [comment]
Step 1: One-time multi-year update to ICD-10-CM codes is done. Previous table ICD_9_10_CM_Complete.xlsx had through 2018, so downloaded ICD-10-CM code descriptions in tabular order and bound all unique rows together. Old version of ICD_9_10_CM_Complete is in archive folder in case issues arise.

**Comment by elikern-kc** [comment]
This has been completed!
