### ISSUE TITLE
Create geo_kc flag for claims.final_mcaid_elig_timevar table on HHSAW

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/Medicaid#161]
Hi all,

Danny fixed this issue for the mcaid_mcaire data awhile back, but I don't think this was every done for the mcaid-only data. There is no geo_kc column in the claims.final_mcaid_elig_timevar table. We need to add this so that the claims_elig function is appropriately calculating time spent in KC according to APDE's approved method.

@preason66 … thanks for this. I've updated the code and am rerunning right now. I'll also ensure that parallel changes are made in the housing repo and will update the timevar there as well. 

@alastairmatheson … I don't think there is anything for you to do on this issue. I'll close it when I submit a pull request later.

_Originally posted by @dcolombara in https://github.com/PHSKC-APDE/claims_data/issues/107#issuecomment-591688952_

**Comment by kai-fukutaki** [comment]
Resolved by https://github.com/PHSKC-APDE/claims_data/pull/176

**Comment by elikern-kc** [comment]
@Fukutaki, ***@***.***> - good work with this!

Next step is to modify the claims_elig function so that the geo_kc_min parameter works correctly.

I'm assuming you have to modify the code starting here: https://github.com/PHSKC-APDE/claims_data/blob/46c15c52b22bbc70c5879d251595bf0e5527f5e9/R/claims_elig.R#L1333

Perhaps by adding code from https://github.com/PHSKC-APDE/claims_data/blob/46c15c52b22bbc70c5879d251595bf0e5527f5e9/R/claims_elig.R#L1331 so that the geo_kc and geo_kc_pct variables get created for "mcaid" data.

Thanks!

Eli

Eli Kern MPH RN | Senior Epidemiologist (he/him)
Assessment, Policy Development, and Evaluation<http://www.kingcounty.gov/health/data>
Public Health - Seattle and King County
phone: 206.263.8727 | email: ***@***.***<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by kai-fukutaki** [comment]
Resolved by https://github.com/PHSKC-APDE/claims_data/pull/179

Tested using https://github.com/PHSKC-APDE/pers_eli/blob/main/qa_checks/claims_elig_geo_kc_min_test.R
